# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
excerpt_separator: ""

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#


title: Cungen's Blog
tagline: A LIFELONG PROCESS
author:
    name: Cungen Jiang
    email: 1360571582@qq.com
    github: cungen
    twitter: Jcungen
    feedburner:

# pagination
paginate: 5

safe: true

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
production_url: http://iamroot.cn

# All material design specific configurations are namespaced into this hash
MD:
    version: 0.0.1

    BASE_PATH: false
    ASSET_PATH: false


    # These paths are to the main pages Jekyll-Bootstrap ships with.
    archive_path: /archive.html
    categories_path: /categories.html
    tags_path: /tags.html
    atom_path: /atom.xml
    rss_path: /rss.xml

    analytics :
        provider : cnzz
